name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:  
      - main 

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: print Hello
        run: echo "Hello World"
